<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sean Vieau">
<meta name="dcterms.date" content="2024-11-30">

<title>The Opioid Epidemic in Colorado: A Geospatial Analysis – Sean Vieau Portfolio</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../../site_libs/kePrint-0.0.1/kePrint.js"></script>

<link href="../../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">



</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Sean Vieau Portfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-advanced-data-analyses-(rsas" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Advanced Data Analyses (R/SAS)</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-advanced-data-analyses-(rsas">    
        <li>
    <a class="dropdown-item" href="../../Project_1_Regression/Project_1_Regression_R/Project_1_Regression.html">
 <span class="dropdown-text">Regression (R)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Project_1_Regression/Project_1_Regression_SAS/Project_1_Regression_SAS.html">
 <span class="dropdown-text">Regression (SAS)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Project_2/Project_2_R/Code/Project2.html">
 <span class="dropdown-text">MLR With Confounding and Interaction (R)</span></a>
  </li>  
        <li class="dropdown-header">MLR With Confounding and Interaction (SAS)</li>
        <li>
    <a class="dropdown-item" href="../../Project_2/Project_2_R/Code/Project2LMM.html">
 <span class="dropdown-text">Linear Mixed Model (R)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Project_2/Project_2_SAS/Code/Linear_Mixed_Modxbcel_SAS.qmd">
 <span class="dropdown-text">Linear Mixed Model (SAS)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Project_3_Predictive_Modelling/Project_3_R/Code/Project_3_Predictive_Modelling.html">
 <span class="dropdown-text">Predictive Modelling (R)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Project_3_Predictive_Modelling/Project_3_SAS/Code/Project_3_Predictive_Modelling_SAS.html">
 <span class="dropdown-text">Predictive Modelling (SAS)</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../Data_Wrangling/Treadmill_Data_Cleaning/Code/Automated_Treadmill_Data_Cleaning.html"> 
<span class="menu-text">Data Wrangling (Python)</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-data-management-(sas" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Data Management (SAS)</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-data-management-(sas">    
        <li>
    <a class="dropdown-item" href="../../Data_Management_(SAS)/Project_1/Project_1_Importing.html">
 <span class="dropdown-text">Project 1 - Importing</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Data_Management_(SAS)/Project_3/Project3.html">
 <span class="dropdown-text">Project 3 - Data Set Creation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Data_Management_(SAS)/Project_5/Project_5_Report_and_Analysis.html">
 <span class="dropdown-text">Project 5 - Report and Analysis</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-statistical-consulting-(r" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Statistical Consulting (R)</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-statistical-consulting-(r">    
        <li>
    <a class="dropdown-item" href="../../Statistical_Consulting/Vieau_Project_01/Code/Megan_Watson_Project.html">
 <span class="dropdown-text">Scope of Work and Negative Binomial Regression (R)</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-data-viz-(r" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Data Viz (R)</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-data-viz-(r">    
        <li>
    <a class="dropdown-item" href="../../Data_Visualization/Cancer_Animations/Gapminder_Cancer_Animations.html">
 <span class="dropdown-text">Animated Plots (R)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Statistical_Consulting/Opioid_Epidemic/GeoSpatial_Opioid_Epidemic.html">
 <span class="dropdown-text">Geospatial Analysis (R)</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../Resume/Publications_and_Presentations.html"> 
<span class="menu-text">Publications/Presentations</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#data-preparation" id="toc-data-preparation" class="nav-link" data-scroll-target="#data-preparation">Data Preparation</a>
  <ul class="collapse">
  <li><a href="#variable-creation" id="toc-variable-creation" class="nav-link" data-scroll-target="#variable-creation">Variable Creation</a></li>
  </ul></li>
  <li><a href="#analysis-one" id="toc-analysis-one" class="nav-link" data-scroll-target="#analysis-one">Analysis One</a>
  <ul class="collapse">
  <li><a href="#mental-health-vs-substance-abuse-treatment-facility" id="toc-mental-health-vs-substance-abuse-treatment-facility" class="nav-link" data-scroll-target="#mental-health-vs-substance-abuse-treatment-facility">Mental Health vs Substance Abuse Treatment Facility</a>
  <ul class="collapse">
  <li><a href="#visualize-distribution-of-facilities-across-colorado" id="toc-visualize-distribution-of-facilities-across-colorado" class="nav-link" data-scroll-target="#visualize-distribution-of-facilities-across-colorado">Visualize Distribution of Facilities Across Colorado</a></li>
  <li><a href="#descriptive-statistics" id="toc-descriptive-statistics" class="nav-link" data-scroll-target="#descriptive-statistics">Descriptive Statistics</a></li>
  <li><a href="#statistical-inference" id="toc-statistical-inference" class="nav-link" data-scroll-target="#statistical-inference">Statistical Inference</a></li>
  <li><a href="#summary-1" id="toc-summary-1" class="nav-link" data-scroll-target="#summary-1">Summary</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#analysis-two" id="toc-analysis-two" class="nav-link" data-scroll-target="#analysis-two">Analysis Two</a>
  <ul class="collapse">
  <li><a href="#naltrexone-and-buprenorphine-use" id="toc-naltrexone-and-buprenorphine-use" class="nav-link" data-scroll-target="#naltrexone-and-buprenorphine-use">Naltrexone and Buprenorphine Use</a>
  <ul class="collapse">
  <li><a href="#visualize-distribution-of-facilities-across-colorado-1" id="toc-visualize-distribution-of-facilities-across-colorado-1" class="nav-link" data-scroll-target="#visualize-distribution-of-facilities-across-colorado-1">Visualize Distribution of Facilities Across Colorado</a></li>
  <li><a href="#descriptive-statistics-1" id="toc-descriptive-statistics-1" class="nav-link" data-scroll-target="#descriptive-statistics-1">Descriptive Statistics</a></li>
  <li><a href="#sensitivity-analysis" id="toc-sensitivity-analysis" class="nav-link" data-scroll-target="#sensitivity-analysis">Sensitivity Analysis</a></li>
  <li><a href="#statistical-inference-1" id="toc-statistical-inference-1" class="nav-link" data-scroll-target="#statistical-inference-1">Statistical Inference</a></li>
  <li><a href="#summary-2" id="toc-summary-2" class="nav-link" data-scroll-target="#summary-2">Summary</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#results-and-conclusion" id="toc-results-and-conclusion" class="nav-link" data-scroll-target="#results-and-conclusion">Results and Conclusion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">The Opioid Epidemic in Colorado: A Geospatial Analysis</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Sean Vieau </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 30, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>This is the final project for BIOS 6640: R for Data Science. In this project we analyze spatial variation patterns in the presence of Behavioral Health Treatment Service Providers throughout Colorado to investigate the opioid epidemic.</p>
<p><img src="images/clipboard-3840054476.png" class="img-fluid" style="width:90.0%">Background</p>
<p>The opioid epidemic is a significant public health crisis in Colorado, with severe impacts on communities, families, and individuals themselves. Prescription pain killers such as oxycodone and hydrocodone are significant causes of opioid addiction, with approximately 70% of heroin users in Colorado reporting that their drug use began with these prescription medications (1). Additionally, fentanyl overdoses have increased by 10x since 2016, with the number of deaths from opioid overdose increasing by 54% from 2019 to 2020 alone (2).</p>
<p>The data set used for this analysis is from the Substance Abuse and Mental Health Services Administration (SAMHSA) in collaboration from the Colorado Public Health and Environment Department (CDPHE), and tracks the different substance use treatment facilities in Colorado. This data set includes the geospatial location (latitude and longitude) of each facility, as well as the type (e.g.&nbsp;mental health facility). The two questions that will be addressed are:</p>
<ol type="1">
<li><p>Are the spatial distributions of Behavioral Health Treatment Service Providers through-out Colorado different by Facility Type?</p></li>
<li><p>Are the spatial distributions of Behavioral Health Treatment Service Providers through-out Colorado different based on whether Naltrexone or Buprenorphine is used in treatment?</p></li>
</ol>
</section>
<section id="data-preparation" class="level1">
<h1>Data Preparation</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(naniar) <span class="co"># Used to visualize missing data</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra) <span class="co"># Used for pretty printing (kable_styling)</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(table1) <span class="co"># Used to make Table 1</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(spatstat) <span class="co"># For running geospatial analyses</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggmap) <span class="co"># For plotting geospatial data with stadia</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Read in data set</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(r<span class="st">"(C:\Users\sviea\Documents\R for Data Science\SAMHSA.csv)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 506 Columns: 42
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (34): Provider_Name, Provider_Name2, Address, Address2, City, State, Co...
dbl   (6): X, Y, OBJECTID, Zip, LATITUDE, LONGITUDE
lgl   (1): Methadone_Detoxification
dttm  (1): Date_Last_Update

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine data set</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pretty_print</span>(<span class="fu">head</span>(data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">X</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Y</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">OBJECTID</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Provider_Name</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Provider_Name2</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Address</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Address2</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">City</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">State</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Zip</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">County</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Phone</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Website_URL</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Date_Last_Update</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Type_</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Detoxification</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Mental_Health</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Substance_Abuse</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Transitional_Housing</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Opiod_Treatment_Settings</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">SAMHSA_Cert_Opioid_Treatment_Program</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Buprenorphine_Maintenance</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Buprenorphine_Maintenance_for_Predetermined_Time</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Buprenorphine_Detoxification</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Buprenorphine_used_in_Treatment</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Naltrexone_used_in_Treatment</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Methadone_Maintenance</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Methadone_Maintenance_for_Predetermined_time</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Methadone_Detoxification</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Prescribes_administers_Buprenorphine</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Prescribes_administers_Naltrexone</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Relapse_prevention_from_Naltrexone</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Use_methadone_buprenorphine_for_pain_mgmt_emergency</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Accepts_clients_on_opioid_medication</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Do_not_use_medication_for_Opioid_Addiction</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Does_not_treat_Opioid_Addiction</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Facility_Type</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Age_Groups_Served</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Date_Data_Published_CDPHE</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Directions</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">LATITUDE</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">LONGITUDE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">-105.0973</td>
<td style="text-align: right;">39.57858</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Shiloh House</td>
<td style="text-align: left;">Estes</td>
<td style="text-align: left;">7623 South Estes Court</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Littleton</td>
<td style="text-align: left;">CO</td>
<td style="text-align: right;">80128</td>
<td style="text-align: left;">Jefferson</td>
<td style="text-align: left;">303-932-9599</td>
<td style="text-align: left;">http://shilohhouse.org/</td>
<td style="text-align: left;">2018-03-06 16:18:03</td>
<td style="text-align: left;">Mental health treatment</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Mental health treatment</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">n/a</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Residential treatment center (RTC) for children</td>
<td style="text-align: left;">Children and Adolescents</td>
<td style="text-align: left;">October 2018</td>
<td style="text-align: left;">https://maps.google.com/?q=7623 South Estes Court, Littleton, CO 80128</td>
<td style="text-align: right;">39.57858</td>
<td style="text-align: right;">-105.0973</td>
</tr>
<tr class="even">
<td style="text-align: right;">-105.0856</td>
<td style="text-align: right;">39.58636</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">Shiloh House</td>
<td style="text-align: left;">Yarrow</td>
<td style="text-align: left;">7227 South Yarrow Court</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Littleton</td>
<td style="text-align: left;">CO</td>
<td style="text-align: right;">80128</td>
<td style="text-align: left;">Jefferson</td>
<td style="text-align: left;">303-932-9599</td>
<td style="text-align: left;">http://shilohhouse.org/</td>
<td style="text-align: left;">2018-03-06 16:18:04</td>
<td style="text-align: left;">Mental health treatment</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Mental health treatment</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">n/a</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Residential treatment center (RTC) for children</td>
<td style="text-align: left;">Children and Adolescents</td>
<td style="text-align: left;">October 2018</td>
<td style="text-align: left;">https://maps.google.com/?q=7227 South Yarrow Court, Littleton, CO 80128</td>
<td style="text-align: right;">39.58636</td>
<td style="text-align: right;">-105.0856</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-105.0708</td>
<td style="text-align: right;">39.59042</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">Shiloh Home Inc</td>
<td style="text-align: left;">Portland</td>
<td style="text-align: left;">6629 West Portland Avenue</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Littleton</td>
<td style="text-align: left;">CO</td>
<td style="text-align: right;">80128</td>
<td style="text-align: left;">Jefferson</td>
<td style="text-align: left;">303-973-9677</td>
<td style="text-align: left;">http://www.shilohhouse.org</td>
<td style="text-align: left;">2017-02-27 11:25:37</td>
<td style="text-align: left;">Mental health treatment</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Mental health treatment</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">n/a</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Residential treatment center (RTC) for children</td>
<td style="text-align: left;">Children and Adolescents</td>
<td style="text-align: left;">October 2018</td>
<td style="text-align: left;">https://maps.google.com/?q=6629 West Portland Avenue, Littleton, CO 80128</td>
<td style="text-align: right;">39.59042</td>
<td style="text-align: right;">-105.0708</td>
</tr>
<tr class="even">
<td style="text-align: right;">-105.0434</td>
<td style="text-align: right;">39.75941</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">Tennyson Center for Children at</td>
<td style="text-align: left;">Colorado Christian Home</td>
<td style="text-align: left;">2950 Tennyson Street</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Denver</td>
<td style="text-align: left;">CO</td>
<td style="text-align: right;">80212</td>
<td style="text-align: left;">Denver</td>
<td style="text-align: left;">303-433-2541</td>
<td style="text-align: left;">http://www.tennysoncenter.org</td>
<td style="text-align: left;">2017-02-27 11:25:37</td>
<td style="text-align: left;">Mental health treatment</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Mental health treatment</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">n/a</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Residential treatment center (RTC) for children</td>
<td style="text-align: left;">Children and Adolescents</td>
<td style="text-align: left;">October 2018</td>
<td style="text-align: left;">https://maps.google.com/?q=2950 Tennyson Street, Denver, CO 80212</td>
<td style="text-align: right;">39.75941</td>
<td style="text-align: right;">-105.0434</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-105.0354</td>
<td style="text-align: right;">39.77446</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">Mount Saint Vincent Home</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">4159 Lowell Boulevard</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Denver</td>
<td style="text-align: left;">CO</td>
<td style="text-align: right;">80211</td>
<td style="text-align: left;">Denver</td>
<td style="text-align: left;">303-458-7220 x238</td>
<td style="text-align: left;">http://www.msvhome.org</td>
<td style="text-align: left;">2017-06-15 09:36:46</td>
<td style="text-align: left;">Mental health treatment</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Mental health treatment</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">n/a</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Residential treatment center (RTC) for children</td>
<td style="text-align: left;">Children and Adolescents</td>
<td style="text-align: left;">October 2018</td>
<td style="text-align: left;">https://maps.google.com/?q=4159 Lowell Boulevard, Denver, CO 80211</td>
<td style="text-align: right;">39.77446</td>
<td style="text-align: right;">-105.0354</td>
</tr>
<tr class="even">
<td style="text-align: right;">-104.9922</td>
<td style="text-align: right;">39.85018</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">Shiloh Home Inc</td>
<td style="text-align: left;">Sanctuary</td>
<td style="text-align: left;">8461 Delaware Street</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Denver</td>
<td style="text-align: left;">CO</td>
<td style="text-align: right;">80260</td>
<td style="text-align: left;">Adams</td>
<td style="text-align: left;">303-933-1393</td>
<td style="text-align: left;">http://www.shilohhouse.org</td>
<td style="text-align: left;">2017-02-27 11:25:37</td>
<td style="text-align: left;">Mental health treatment</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Mental health treatment</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">n/a</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Residential treatment center (RTC) for children</td>
<td style="text-align: left;">Children and Adolescents</td>
<td style="text-align: left;">October 2018</td>
<td style="text-align: left;">https://maps.google.com/?q=8461 Delaware Street, Denver, CO 80260</td>
<td style="text-align: right;">39.85018</td>
<td style="text-align: right;">-104.9922</td>
</tr>
</tbody>
</table>


</div>
</div>
<section id="examine-missingness" class="level4">
<h4 class="anchored" data-anchor-id="examine-missingness">Examine Missingness</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine Missingness</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">vis_miss</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="GeoSpatial_Opioid_Epidemic_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>As noted in the project description, many variables have values of 0 coded as <code>NA</code>.</p>
</section>
<section id="variable-creation" class="level2">
<h2 class="anchored" data-anchor-id="variable-creation">Variable Creation</h2>
<p>We will first create a variable for whether the facility is a mental health treatment or substance abuse treatment facility.</p>
<section id="facility-type" class="level4">
<h4 class="anchored" data-anchor-id="facility-type">Facility Type</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine Facility Types</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pretty_print</span>(<span class="fu">table</span>(data<span class="sc">$</span>Type_))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Var1</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Freq</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Detoxification</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Detoxification, Substance abuse treatment</td>
<td style="text-align: right;">26</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Detoxification, Substance abuse treatment, Transitional housing or halfway house</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mental health treatment</td>
<td style="text-align: right;">149</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Substance abuse treatment</td>
<td style="text-align: right;">307</td>
</tr>
<tr class="even">
<td style="text-align: left;">Substance abuse treatment, Transitional housing or halfway house</td>
<td style="text-align: right;">16</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Transitional housing or halfway house</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>We will condense these descriptions into two facility types:</p>
<ul>
<li><p>Substance Abuse Treatment</p></li>
<li><p>Mental Abuse Treatment</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Aggregate facility types</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">|&gt;</span> </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">facility =</span> <span class="fu">ifelse</span>(Type_ <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Mental health treatment"</span>, <span class="st">"Transitional housing or halfway house"</span>), <span class="st">"Mental Health Treatment"</span>, <span class="st">"Substance Abuse Treatment"</span>))</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Create table of facility type</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="fu">pretty_print</span>(<span class="fu">table</span>(data<span class="sc">$</span>facility))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Var1</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Freq</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mental Health Treatment</td>
<td style="text-align: right;">150</td>
</tr>
<tr class="even">
<td style="text-align: left;">Substance Abuse Treatment</td>
<td style="text-align: right;">356</td>
</tr>
</tbody>
</table>


</div>
</div>
</section>
<section id="naltrexone-or-buprenorphrine-used-in-treatment" class="level4">
<h4 class="anchored" data-anchor-id="naltrexone-or-buprenorphrine-used-in-treatment">Naltrexone or Buprenorphrine Used in Treatment</h4>
<p>For question 2 we need to dummy code whether the facility uses naltrexone or buprenorphine in treatment</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create dummy variables</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">|&gt;</span> </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">nal =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(Naltrexone_used_in_Treatment), <span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">bup =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(Buprenorphine_used_in_Treatment), <span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">nal_bup =</span> <span class="fu">ifelse</span>(<span class="sc">!</span><span class="fu">is.na</span>(Buprenorphine_used_in_Treatment) <span class="sc">|</span> <span class="sc">!</span><span class="fu">is.na</span>(Naltrexone_used_in_Treatment), <span class="st">"Naltrexone or Buprenorphine Used"</span>, <span class="st">"Neither Used"</span>))</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="fu">pretty_print</span>(<span class="fu">table</span>(data<span class="sc">$</span>nal_bup))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Var1</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Freq</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Naltrexone or Buprenorphine Used</td>
<td style="text-align: right;">98</td>
</tr>
<tr class="even">
<td style="text-align: left;">Neither Used</td>
<td style="text-align: right;">408</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>There are 408 facilities that do not use naltrexone or buprenorphine, and 98 that use at least one.</p>
</section>
<section id="summary" class="level4">
<h4 class="anchored" data-anchor-id="summary">Summary</h4>
<p>We successfully created variables for <code>facility</code> type (for question 1), and use of naltrexone or buprenorphine (for question 2)</p>
</section>
</section>
</section>
<section id="analysis-one" class="level1">
<h1>Analysis One</h1>
<section id="mental-health-vs-substance-abuse-treatment-facility" class="level2">
<h2 class="anchored" data-anchor-id="mental-health-vs-substance-abuse-treatment-facility">Mental Health vs Substance Abuse Treatment Facility</h2>
<p>To answer question one “Are the spatial distributions of Behavioral Health Treatment Service Providers through-out Colorado different by Facility Type” we will first visualize the difference in distributions over a map of Colorado. We will then test whether these distributions are significantly different using the estimated K-Functions.</p>
<section id="visualize-distribution-of-facilities-across-colorado" class="level3">
<h3 class="anchored" data-anchor-id="visualize-distribution-of-facilities-across-colorado">Visualize Distribution of Facilities Across Colorado</h3>
<p>First, let us begin by visualizing the distribution of behavioral care facilities across Colorado, separated by mental health vs substance abuse treatment.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># API Key from https://client.stadiamaps.com/signup</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Register Stadia API so we can use it to retrieve maps</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="fu">register_stadiamaps</span>(<span class="at">key =</span> <span class="st">"4a4ea0df-9bd4-4ce8-a9ff-f1a7d86c0da9"</span>)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the bounding box for Colorado</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>colo <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">left =</span> <span class="sc">-</span><span class="dv">109</span>, <span class="at">bottom =</span> <span class="dv">37</span>, <span class="at">right =</span> <span class="sc">-</span><span class="dv">102</span>, <span class="at">top =</span> <span class="dv">41</span>)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Retrieve and plot the stamen toner map of colorado</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>colo_map <span class="ot">&lt;-</span> <span class="fu">get_stadiamap</span>(colo, <span class="at">zoom =</span> <span class="dv">8</span>, <span class="at">maptype =</span> <span class="st">"stamen_terrain"</span>) <span class="sc">|&gt;</span> <span class="fu">ggmap</span>()</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the distribution of behavioral care facilities across Colorado, separated by facility type</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>colo_map <span class="sc">+</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(LONGITUDE, LATITUDE), <span class="at">data =</span> data, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_density_2d</span>(<span class="fu">aes</span>(LONGITUDE, LATITUDE, <span class="at">fill =</span> ..level..), <span class="at">data =</span> data, <span class="at">geom =</span> <span class="st">"polygon"</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradient2</span>(<span class="st">"Facility</span><span class="sc">\n</span><span class="st">Propensity"</span>, <span class="at">low =</span> <span class="st">"white"</span>, <span class="at">mid =</span> <span class="st">"yellow"</span>, <span class="at">high =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>facility, <span class="at">ncol=</span><span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Behavioral Health Treatment Service Providers throughout Colorado"</span>,</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Longitude"</span>,</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Latitude"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="GeoSpatial_Opioid_Epidemic_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>It appears that there is a <em>higher concentration of substance abuse treatment facilities</em> around Denver compared to mental health treatment facilities. This could be due to the smaller sample size of mental health treatment facilities however.</p>
</section>
<section id="descriptive-statistics" class="level3">
<h3 class="anchored" data-anchor-id="descriptive-statistics">Descriptive Statistics</h3>
<p>We will perform a simple density plot to compare the densities of both treatment facilities.</p>
<section id="create-geospatial-objects" class="level4">
<h4 class="anchored" data-anchor-id="create-geospatial-objects">Create Geospatial Objects</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Code adjusted from SpatialPart2.Rmd from class</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Create owin and ppp objects</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>bbx <span class="ot">&lt;-</span> <span class="fu">owin</span>(<span class="at">xrange=</span><span class="fu">range</span>(data<span class="sc">$</span>LONGITUDE),<span class="at">yrange=</span><span class="fu">range</span>(data<span class="sc">$</span>LATITUDE))</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">ppp</span>(data<span class="sc">$</span>LONGITUDE,data<span class="sc">$</span>LATITUDE,<span class="at">window=</span>bbx)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Get row length of dataset</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">dim</span>(data)[<span class="dv">1</span>]</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a blank vector with 0's to that specification</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>data_vec <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>,n)</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Search facility column for mental health units</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>tmp <span class="ot">&lt;-</span> <span class="fu">grep</span>(<span class="st">"Mental"</span>, data<span class="sc">$</span>facility)</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Mark them as 1</span></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>data_vec[tmp] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Ensure values are a factor and not numeric</span></span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>data_vec_fact <span class="ot">&lt;-</span> <span class="fu">factor</span>(data_vec, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Substance Abuse Facility"</span>, <span class="st">"Mental Health Facility"</span>))</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Use the ppp function from the spatstat package to create a point pattern object X.m1</span></span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>X.m1 <span class="ot">&lt;-</span> <span class="fu">ppp</span>(data<span class="sc">$</span>LONGITUDE,data<span class="sc">$</span>LATITUDE,<span class="at">window=</span>bbx,<span class="at">marks=</span>data_vec_fact)</span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Create Plot</span></span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(X.m1)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="GeoSpatial_Opioid_Epidemic_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the densities of each treatment facility type</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pretty_print</span>(<span class="fu">intensity</span>(X.m1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Substance Abuse Facility</td>
<td style="text-align: right;">13.803652</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mental Health Facility</td>
<td style="text-align: right;">5.816146</td>
</tr>
</tbody>
</table>


</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(<span class="fu">split</span>(X.m1)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="GeoSpatial_Opioid_Epidemic_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="interpretation" class="level4">
<h4 class="anchored" data-anchor-id="interpretation">Interpretation</h4>
<p>Substance Abuse Facility: The intensity is approximately 13.80 facilities per unit area.</p>
<p>Mental Health Facility: The intensity is approximately 5.82 facilities per unit area.</p>
<p>This means that Substance Abuse Facilities are more densely distributed compared to Mental Health Facilities in Colorado.</p>
</section>
</section>
<section id="statistical-inference" class="level3">
<h3 class="anchored" data-anchor-id="statistical-inference">Statistical Inference</h3>
<p>Now that we have visualized the distribution of facility types across Colorado, let’s test whether there is a significant difference in the distribution between mental health and substance abuse treatment facilities.</p>
<p>This spatial data analysis will use the <strong>K-Function</strong>. This is the empirical distribution of the pairwise distance between points. It includes the variance based on bootstrapping, and describes the clustering/dispersion of points.</p>
<section id="perform-statistical-inference" class="level4">
<h4 class="anchored" data-anchor-id="perform-statistical-inference">Perform Statistical Inference</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="GeoSpatial_Opioid_Epidemic_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="GeoSpatial_Opioid_Epidemic_files/figure-html/unnamed-chunk-10-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>1, 2, 3, .5....10....15....20....25....30....35....40....45....50..
..55....60....65....70....75....80....85....90....95....100....105....110
....115....120....125....130....135....140....145....150....155....160....165...
.170....175....180....185....190....195....200....205....210....215....220....225.
...230....235....240....245....250....255....260....265....270....275....280....
285....290....295....300....305....310....315....320....325....330....335....340..
..345....350....355
356.
1, 2, 3, 4.6.8.10.12.14.16.18.20.22.24.26.28.30.32.34
.36.38.40.42.44.46.48.50.52.54.56.58.60.62.64.66.68.70.72.74
.76.78.80.82.84.86.88.90.92.94.96.98.100.102.104.106.108.110.112.114
.116.118.120.122.124.126.128.130.132.134.136.138.140.142.144.146.148.
150.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="GeoSpatial_Opioid_Epidemic_files/figure-html/unnamed-chunk-10-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="interpretation-1" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-1">Interpretation</h4>
<p>The K-function measures the number of points within a given distance from a typical point, compared to what would be expected under complete spatial randomness (CSR). The null hypothesis here is that of complete spatial randomness (i.e.&nbsp;the red dotted line).</p>
<p>The estimated K-functions for both mental health treatment and substance abuse treatment facilities lie above the theoretical K-Function, indicating that the distributions for each facility type do not exhibit complete spatial randomness. Additionally, since the 95% CIs do not overlap, we can conclude that this difference is statistically significant.</p>
<p>The estimated K-Function for substance abuse treatment facilities is significantly greater than that of mental health treatment clinics indicating that the substance abuse treatment facilities are significantly more clustered than the mental health treatment clinics.</p>
</section>
</section>
<section id="summary-1" class="level3">
<h3 class="anchored" data-anchor-id="summary-1">Summary</h3>
<p>We have discovered that the distributions for both facility types are not random, and that substance abuse clinics are more clustered together compared to mental health clinics, with a approximately 13.80 Substance Abuse facilities per unit area, and approximately 5.82 Mental Health facilities per unit area.</p>
</section>
</section>
</section>
<section id="analysis-two" class="level1">
<h1>Analysis Two</h1>
<section id="naltrexone-and-buprenorphine-use" class="level2">
<h2 class="anchored" data-anchor-id="naltrexone-and-buprenorphine-use">Naltrexone and Buprenorphine Use</h2>
<p>To answer question two, “Are the spatial distributions of Behavioral Health Treatment Service Providers through-out Colorado different based on whether Naltrexone or Buprenorphine is used in treatment?” we will examine the quadrat plots and compare distributions using the estimated K-Functions.</p>
<section id="visualize-distribution-of-facilities-across-colorado-1" class="level3">
<h3 class="anchored" data-anchor-id="visualize-distribution-of-facilities-across-colorado-1">Visualize Distribution of Facilities Across Colorado</h3>
<p>First, let us begin by visualizing the distribution of facilities that use buprenorphrine or naltrexone across Colorado.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the distribution of behavioral care facilities across Colorado, separated by facility type</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>colo_map <span class="sc">+</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(LONGITUDE, LATITUDE), <span class="at">data =</span> data, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_density_2d</span>(<span class="fu">aes</span>(LONGITUDE, LATITUDE, <span class="at">fill =</span> ..level..), <span class="at">data =</span> data, <span class="at">geom =</span> <span class="st">"polygon"</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradient2</span>(<span class="st">"Facility</span><span class="sc">\n</span><span class="st">Propensity"</span>, <span class="at">low =</span> <span class="st">"white"</span>, <span class="at">mid =</span> <span class="st">"yellow"</span>, <span class="at">high =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>nal_bup, <span class="at">ncol=</span><span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Behavioral Health Treatment Service Providers throughout Colorado"</span>,</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Longitude"</span>,</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Latitude"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="GeoSpatial_Opioid_Epidemic_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>It appears that facilities that use naltrexone or buprenorphine may be more localized around Denver compared to facilities that do not.</p>
</section>
<section id="descriptive-statistics-1" class="level3">
<h3 class="anchored" data-anchor-id="descriptive-statistics-1">Descriptive Statistics</h3>
<p>We will be examining the quadrat plots to examine the distributions of facilities.</p>
<section id="prepare-and-split-the-data" class="level4">
<h4 class="anchored" data-anchor-id="prepare-and-split-the-data">Prepare and Split the Data</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Split the data into two groups</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>bup_or_nal <span class="ot">&lt;-</span> <span class="fu">subset</span>(data, nal_bup <span class="sc">==</span> <span class="st">"Naltrexone or Buprenorphine Used"</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>neither <span class="ot">&lt;-</span> <span class="fu">subset</span>(data, nal_bup <span class="sc">==</span> <span class="st">"Neither Used"</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Create ppp for bup or nal data set</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>bup_or_nal_ppp <span class="ot">&lt;-</span> <span class="fu">ppp</span>(bup_or_nal<span class="sc">$</span>LONGITUDE, bup_or_nal<span class="sc">$</span>LATITUDE, <span class="at">window=</span>bbx)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Create ppp for neither data set</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>neither_ppp <span class="ot">&lt;-</span> <span class="fu">ppp</span>(neither<span class="sc">$</span>LONGITUDE, neither<span class="sc">$</span>LATITUDE, <span class="at">window=</span>bbx)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="perform-quadrat-count" class="level4">
<h4 class="anchored" data-anchor-id="perform-quadrat-count">Perform Quadrat Count</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the number of quadrats</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>nx <span class="ot">&lt;-</span> <span class="dv">5</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>ny <span class="ot">&lt;-</span> <span class="dv">5</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Quadrat counts for Bup or Nal and Neither</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>bup_or_nal_quadrat <span class="ot">&lt;-</span> <span class="fu">quadratcount</span>(bup_or_nal_ppp, <span class="at">nx =</span> nx, <span class="at">ny =</span> ny)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>neither_quadrat <span class="ot">&lt;-</span> <span class="fu">quadratcount</span>(neither_ppp, <span class="at">nx =</span> nx, <span class="at">ny =</span> ny)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="plot-quadrat-counts" class="level4">
<h4 class="anchored" data-anchor-id="plot-quadrat-counts">Plot Quadrat Counts</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot quadrat counts for Bup or Nal</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(bup_or_nal_quadrat, <span class="at">col=</span><span class="st">"blue"</span>, <span class="at">main =</span> <span class="st">"Naltrexone or Buprenorphine Used"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="GeoSpatial_Opioid_Epidemic_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot quadrat counts for Neither</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(neither_quadrat, <span class="at">col=</span><span class="st">"red"</span>, <span class="at">main =</span> <span class="st">"Neither Used"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="GeoSpatial_Opioid_Epidemic_files/figure-html/unnamed-chunk-14-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="compare-quadrat-counts" class="level4">
<h4 class="anchored" data-anchor-id="compare-quadrat-counts">Compare Quadrat Counts</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary of quadrat counts</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">quadrat.test</span>(bup_or_nal_quadrat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Some expected counts are small; chi^2 approximation may be inaccurate</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Chi-squared test of CSR using quadrat counts

data:  
X2 = 525.98, df = 24, p-value &lt; 0.00000000000000022
alternative hypothesis: two.sided

Quadrats: 5 by 5 grid of tiles</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quadrat.test</span>(neither_quadrat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Chi-squared test of CSR using quadrat counts

data:  
X2 = 1415.8, df = 24, p-value &lt; 0.00000000000000022
alternative hypothesis: two.sided

Quadrats: 5 by 5 grid of tiles</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Chi-squared test for comparison</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>observed_counts <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="fu">as.vector</span>(bup_or_nal_quadrat), <span class="fu">as.vector</span>(neither_quadrat))</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(observed_counts)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in chisq.test(observed_counts): Chi-squared approximation may be
incorrect</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  observed_counts
X-squared = 24.761, df = 24, p-value = 0.4188</code></pre>
</div>
</div>
</section>
<section id="interpretation-2" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-2">Interpretation</h4>
<p>The results for the Chi-squared test of complete spatial randomness for facilities that use nalextrone or buprenorphrine (2 = 525.98, df = 24, p-value &lt; 0.0001) and those that use neither (X2 = 1415.8, df = 24, p-value &lt; 0.0001) are highly significant, indicating that there is spatial preference for both facility types (i.e.&nbsp;they are not CSR).</p>
<p>However, the Pearson Chi-Squared test comparing the distributions of both was not significant (X-squared = 24.761, df = 24, p-value = 0.42), indicating that there is not a significant difference in the distribution of facilities based on nalextrone or buprenorprhine use.</p>
</section>
</section>
<section id="sensitivity-analysis" class="level3">
<h3 class="anchored" data-anchor-id="sensitivity-analysis">Sensitivity Analysis</h3>
<p>We can also perform this analysis as many different bin sizes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the number of quadrats</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>nx <span class="ot">&lt;-</span> <span class="dv">3</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>ny <span class="ot">&lt;-</span> <span class="dv">3</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Quadrat counts for Bup or Nal and Neither</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>bup_or_nal_quadrat <span class="ot">&lt;-</span> <span class="fu">quadratcount</span>(bup_or_nal_ppp, <span class="at">nx =</span> nx, <span class="at">ny =</span> ny)</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>neither_quadrat <span class="ot">&lt;-</span> <span class="fu">quadratcount</span>(neither_ppp, <span class="at">nx =</span> nx, <span class="at">ny =</span> ny)</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary of quadrat counts</span></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a><span class="fu">quadrat.test</span>(bup_or_nal_quadrat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Chi-squared test of CSR using quadrat counts

data:  
X2 = 144.45, df = 8, p-value &lt; 0.00000000000000022
alternative hypothesis: two.sided

Quadrats: 3 by 3 grid of tiles</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quadrat.test</span>(neither_quadrat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Chi-squared test of CSR using quadrat counts

data:  
X2 = 623.56, df = 8, p-value &lt; 0.00000000000000022
alternative hypothesis: two.sided

Quadrats: 3 by 3 grid of tiles</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Chi-squared test for comparison</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>observed_counts <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="fu">as.vector</span>(bup_or_nal_quadrat), <span class="fu">as.vector</span>(neither_quadrat))</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(observed_counts)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in chisq.test(observed_counts): Chi-squared approximation may be
incorrect</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  observed_counts
X-squared = 6.4499, df = 8, p-value = 0.597</code></pre>
</div>
</div>
<p>Even at 9 bins total, we get the same results, giving us more confidence in our findings.</p>
</section>
<section id="statistical-inference-1" class="level3">
<h3 class="anchored" data-anchor-id="statistical-inference-1">Statistical Inference</h3>
<p>We will again perform K-Function analyses to compare the distributions between facilities that use nalextrone/buprenorphrine and those that do not.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="GeoSpatial_Opioid_Epidemic_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="GeoSpatial_Opioid_Epidemic_files/figure-html/unnamed-chunk-18-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>1, 2, 3, .5....10....15....20....25....30....35....40....45....50..
..55....60....65....70....75....80....85....90....95....100....105....110
....115....120....125....130....135....140....145....150....155....160....165...
.170....175....180....185....190....195....200....205....210....215....220....225.
...230....235....240....245....250....255....260....265....270....275....280....
285....290....295....300....305....310....315....320....325....330....335....340..
..345....350....355....360....365....370....375....380....385....390....395....400
....405..
408.
1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 
98.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="GeoSpatial_Opioid_Epidemic_files/figure-html/unnamed-chunk-18-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="interpretation-3" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-3">Interpretation</h4>
<p>Here we can see that the CI’s for facilities that use Naltrexone/Buprenorphrine and those that do not overlap, confirming the results from the quadrat plots that these distributions across Colorado are not significantly different.</p>
</section>
</section>
<section id="summary-2" class="level3">
<h3 class="anchored" data-anchor-id="summary-2">Summary</h3>
<p>We discovered that facilities that use naltrexone/buprenorphrine and those that do not both show spatial preference. Additionally, we learned that their distributions did not significantly differ from each other.</p>
</section>
</section>
</section>
<section id="results-and-conclusion" class="level1">
<h1>Results and Conclusion</h1>
<section id="analysis-one-1" class="level4">
<h4 class="anchored" data-anchor-id="analysis-one-1">Analysis One</h4>
<p>To assess question one, facilities were separated by type (NMental Health Treatment = 150, NSubstance Abuse Treatment = 356) (Note: facilities which performed detoxification only were considered substance abuse facilities, and one transitional/halfway house was considered a mental health treatment facility). The location and density of every Behavioral Health Treatment facility was then plotted against a map of Colorado and separated by facility type (see Figure 1). Density plots were then made to compare the intensities between the distribution of substance abuse and mental health facilities (See Figure 2). While both facility types were localized around Denver, substance abuse facilities had an intensity of 13.80 facilities per unit area, compared to mental health facilities which had approximately 5.82 facilities per unit area.</p>
<p>To test whether the distributions between substance abuse vs mental health facilities were statistically significant, we performed spatial data analysis using the estimated K-Functions for each facility type (See Figure 3). The estimated K-functions for both mental health treatment and substance abuse treatment facilities were above the theoretical K-Function, indicating that the distributions for each facility type do not exhibit complete spatial randomness. Additionally, since the 95% CIs do not overlap, we concluded that this difference was statistically significant. Finally, the estimated K-Function for substance abuse treatment facilities was significantly higher than that of mental health treatment clinics, indicating that substance abuse treatment facilities are significantly more clustered than mental health treatment clinics, aligning with the findings from the descriptive statistics.</p>
</section>
<section id="analysis-two-1" class="level4">
<h4 class="anchored" data-anchor-id="analysis-two-1">Analysis Two</h4>
<p>To assess question two, facilities were separated into those that used nalextrone or buprenorphrine during treatment (N = 98), and those that did not (N = 408). The location and density of every Behavioral Health Treatment facility by these categories was then plotted against a map of Colorado (See Figure 4). For descriptive statistics, 5x5 quadrat plots were made (See Figure 5), and the quadrat counts of facilities that use nalextrone or buprenorphrine and those that do not were compared. The results for the Chi-squared test of complete spatial randomness for facilities that use nalextrone or buprenorphrine (X2 = 525.98, df = 24, p-value &lt; 0.0001) and those that use neither (X2 = 1415.80, df = 24, p-value &lt; 0.0001) were highly significant, indicating that there is spatial preference for both facility types (i.e.&nbsp;they are not completely spatially random). However, the Pearson Chi-Squared test comparing the distributions of both facility types to each other was not significant (X2 = 24.761, df = 24, p-value = 0.42), indicating that there is not a significant difference in the distribution of facilities based on nalextrone or buprenorphrine use. A sensitivity analysis using a 3x3 quadrat plot was also conducted, yielding the same findings. To test whether the distributions between facilities that use nalextrone or buprenorphrine and those that do not were significantly different, we performed spatial data analysis using the estimated K-Functions for each facility type (See Figure 6). The findings confirm the results of the descriptive analyses, showing overlap in the 95% confidence intervals in the K-functions for facilities that use nalextrone or buprenorphrine and those that do not, indicating that these distributions are not significantly different from each other.</p>
</section>
<section id="conclusion" class="level4">
<h4 class="anchored" data-anchor-id="conclusion">Conclusion</h4>
<p>In this project we performed a series of descriptive and inferential geospatial analyses to assess the distribution of Behavioral Health Treatment facilities in Colorado. To answer question one, we found that the distribution of mental health and substance abuse treatment facilities was not random. Additionally, we found that substance abuse clinics are more clustered together compared to mental health treatment facilities. In question two, we discovered that facilities that use naltrexone or buprenorphrine and those that do not both show spatial preference and are not randomly distributed. Additionally, we learned that their distributions did not significantly differ from each other.</p>
<section id="strengths-and-limitations" class="level6">
<h6 class="anchored" data-anchor-id="strengths-and-limitations">Strengths and Limitations</h6>
<p>A strength of this study was the combination of descriptive and inferential statistics using geospatial analysis coupled with the high-quality data set provided by SAMHSA, resulting in a robust analysis on the distribution of Behavioral Health Treatment facilities in Colorado. Additionally, a sensitivity analysis using varying sized quadrat plots was performed, showing consistent findings across quadrat sizes. A limitation is that additional analyses, such as the nonparametric test of relative risk for evaluating the dependence between spatial locations and the mark was not used, which could have added to the strength of the analysis. Finally, data on deaths by opioid use for each region was not included, which could have provided much needed context to the extent of the opioid epidemic in Colorado.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/svieau\.quarto\.pub\/portfolio");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>